import { BrowserRouter, Routes, Route, Navigate, useLocation, useNavigate } from "react-router-dom";
import { useEffect } from "react";
import { SurveyProvider, useSurveyContext } from "@/hooks/useSurvey";
import { Landing } from "@/pages/Landing"; import { Intro } from "@/pages/Intro"; import { Consent } from "@/pages/Consent"; import { Survey } from "@/pages/Survey"; import { Concept } from "@/pages/Concept"; import { ThankYou } from "@/pages/ThankYou"; import { Privacy } from "@/pages/Privacy";
function StageRouter(){
 const {state,jumpToStage}=useSurveyContext(); const location=useLocation(); const navigate=useNavigate();
 useEffect(()=>{ const map:Record<typeof state.stage,string>={landing:"/",intro:"/intro",consent:"/consent",survey:"/survey",concept:"/concept","thank-you":"/thank-you"}; const target=map[state.stage]; if(location.pathname!==target && location.pathname!=="/privacy") navigate(target,{replace:true}); },[state.stage,location.pathname,navigate]);
 useEffect(()=>{ const reverse:Record<string,typeof state.stage>={"/":"landing","/intro":"intro","/consent":"consent","/survey":"survey","/concept":"concept","/thank-you":"thank-you"}; const desired=reverse[location.pathname]; if(!desired||desired===state.stage)return; if(desired==="landing"||desired==="intro"||desired==="consent") jumpToStage(desired); else if(desired==="survey"&&state.respondentId) jumpToStage("survey"); else if(desired==="concept"&&state.stage==="survey") jumpToStage("concept"); else if(desired==="thank-you"&&state.completionStatus==="completed") jumpToStage("thank-you"); else navigate("/",{replace:true}); },[location.pathname,state.stage,state.respondentId,state.completionStatus,jumpToStage,navigate]);
 return <Routes><Route path="/" element={<Landing/>}/><Route path="/intro" element={<Intro/>}/><Route path="/consent" element={<Consent/>}/><Route path="/survey" element={<Survey/>}/><Route path="/concept" element={<Concept/>}/><Route path="/thank-you" element={<ThankYou/>}/><Route path="/privacy" element={<Privacy/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes>;
}
export default function App(){return <BrowserRouter><SurveyProvider><StageRouter/></SurveyProvider></BrowserRouter>}
